# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthFoodMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthFoodMe
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Alamofire'
  pod 'NMapsMap'
  pod 'KakaoSDKAuth'  # 사용자 인증
  pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리
  pod 'RealmSwift', '~>10'
  pod 'Firebase/Core', '9.2.0'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Crashlytics'
  pod 'Kingfisher', '~> 7.0'
  pod 'SwiftLint'
  pod 'BSImagePicker', '~> 3.1' 
  pod 'lottie-ios'
  
end
